"""Evaluate a checkpoint and write results.md.

    python scripts/evaluate.py --ckpt /path/to/ckpt_step6000.pt
    python scripts/evaluate.py --ckpt ... --limit 20      # quick check

Scoring happens at the level of the original points, with the training caps
disabled, so the number is comparable with published ScanNet mIoU. Nothing here
invents a figure: a class with no ground truth in the evaluated scenes is
reported as "not present" rather than counted as zero.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import torch
from torch.utils.data import DataLoader
from tqdm import tqdm

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from reify.config import load_config  # noqa: E402
from reify.data import ScanNetDataset, collate  # noqa: E402
from reify.data.labels import SCANNET20_NAMES  # noqa: E402
from reify.eval.inference import panoptic_from_outputs, superpoint_to_point  # noqa: E402
from reify.eval.metrics import ConfusionMatrix, PanopticMeter  # noqa: E402
from reify.models import OneFormer3DLike  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default=None)
    parser.add_argument("--ckpt", required=True)
    parser.add_argument("--split", default=None)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--out", default=None)
    args = parser.parse_args()

    cfg = load_config(args.config)
    split = args.split or cfg.eval.split
    limit = cfg.eval.limit if args.limit is None else args.limit
    out_path = args.out or cfg.eval.results_path

    device = "cuda" if torch.cuda.is_available() else "cpu"
    state = torch.load(args.ckpt, map_location=device)

    # The checkpoint decides the feature width. A model trained on xyz+rgb
    # cannot be evaluated with normals appended, so follow what it recorded.
    use_normals = bool(state.get("use_normals", cfg.data.use_normals))
    backbone = state.get("backbone", cfg.model.backbone)
    step = state.get("step", "unknown")
    print(f"[eval] checkpoint step={step} backbone={backbone} use_normals={use_normals}")

    dataset = ScanNetDataset(
        root=cfg.data.root,
        split=split,
        voxel_size=cfg.data.voxel_size,
        # caps off: this is what makes the number comparable
        max_points=0 if cfg.eval.point_level else cfg.data.max_points,
        max_superpoints=0 if cfg.eval.point_level else cfg.data.max_superpoints,
        use_normals=use_normals,
        cache_dir=cfg.data.cache_dir,
        seed=cfg.data.seed,
        verify=cfg.data.verify,
        return_points=True,
    )
    if limit:
        dataset.scene_ids = dataset.scene_ids[:limit]

    loader = DataLoader(dataset, batch_size=1, shuffle=False,
                        num_workers=cfg.data.num_workers, collate_fn=collate)

    model = OneFormer3DLike(
        num_classes=cfg.model.num_classes,
        in_channels=dataset.in_channels,
        d_model=cfg.model.d_model,
        nhead=cfg.model.nhead,
        num_decoder_layers=cfg.model.num_decoder_layers,
        k_ins=cfg.model.k_ins,
        query_aug_std=0.0,
        backbone=backbone,
    ).to(device)
    model.load_state_dict(state["model"])
    model.eval()

    confusion = ConfusionMatrix(cfg.model.num_classes)
    panoptic = PanopticMeter(cfg.model.num_classes)
    scenes = 0

    with torch.no_grad():
        for batch in tqdm(loader, desc=f"{split}"):
            tensors = {k: (v.to(device) if torch.is_tensor(v) else v) for k, v in batch.items()}
            out = model(tensors)

            sp_sem, sp_inst = panoptic_from_outputs(
                out,
                tensors["sp_mask"],
                num_classes=cfg.model.num_classes,
                mask_threshold=cfg.eval.mask_threshold,
                score_threshold=cfg.eval.score_threshold,
            )

            point_sp = batch["point_sp"][0].to(device)
            pred_sem = superpoint_to_point(sp_sem, point_sp).cpu().numpy()
            pred_inst = superpoint_to_point(sp_inst, point_sp).cpu().numpy()
            gt_sem = batch["point_sem"][0].numpy()
            gt_inst = batch["point_inst"][0].numpy()

            confusion.update(pred_sem, gt_sem)
            panoptic.update(pred_sem, pred_inst, gt_sem, gt_inst)
            scenes += 1

    summary = panoptic.summary()
    miou = confusion.miou()

    print(f"\nmIoU {100 * miou:.1f} | PQ {summary['PQ']:.1f} "
          f"SQ {summary['SQ']:.1f} RQ {summary['RQ']:.1f} over {scenes} scenes")

    report = f"""# Results

Generated by `scripts/evaluate.py`. Every figure below was measured. A class with
no ground truth in the evaluated scenes is reported as "not present" rather than
counted as zero.

| | |
|---|---|
| checkpoint | `{Path(args.ckpt).name}` (step {step}) |
| backbone | **{backbone}** |
| input features | {dataset.in_channels}-dim ({'xyz+rgb+normal' if use_normals else 'xyz+rgb'}) |
| split | {split} |
| scenes evaluated | **{scenes}** of {len(dataset.scene_ids) if not limit else limit} |
| scored at | {'original points, caps disabled' if cfg.eval.point_level else 'superpoints'} |
| voxel size | {cfg.data.voxel_size} m |
| generated | {dt.datetime.now().strftime('%Y-%m-%d %H:%M')} |

## Semantic segmentation

**mIoU {100 * miou:.1f}**, overall accuracy {100 * confusion.accuracy():.1f}

{confusion.as_markdown(SCANNET20_NAMES)}

## Panoptic segmentation

**PQ {summary['PQ']:.1f}**, SQ {summary['SQ']:.1f}, RQ {summary['RQ']:.1f}

Wall and floor are scored as stuff, matching the ScanNet convention that
excludes them from instance evaluation because their instance boundaries are not
consistently annotated.

{panoptic.as_markdown(SCANNET20_NAMES)}
"""

    Path(out_path).write_text(report, encoding="utf-8")
    print(f"[eval] wrote {out_path}")


if __name__ == "__main__":
    main()
